collection: stock-market-data
has_premium: true
licenses:
- name: ODC-PDDL-1.0
  path: http://opendatacommons.org/licenses/pddl/
  title: Open Data Commons Public Domain Dedication and License v1.0
name: finance-vix
resources:
- format: csv
  mediatype: text/csv
  name: vix-daily
  path: data/vix-daily.csv
  schema:
    fields:
    - name: DATE
      type: date
      format: %m/%d/%Y
      description: Date in MM/DD/YYYY format
    - name: OPEN
      type: number
    - name: HIGH
      type: number
    - name: LOW
      type: number
    - name: CLOSE
      type: number
title: CBOE Volatility Index
version: '2.0'
views:
- resources: vix-daily
  name: daily-opening-closing-figures
  title: Daily opening and closing figures
  specType: simple
  spec:
    group: DATE
    series:
      - OPEN
      - CLOSE
    type: line
