on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: make
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update data"
            git push
          fi
